spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration
  flyway:
    locations: classpath:/db/migration


cicoffee:
  auth:
    jwt:
      expires-in: 3600
      refresh-token-expires-in: 182
