spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://92.94.210.134:35432/cicoffee
    username: admin
    password: admin
    initialization-mode: never
  flyway:
    locations: classpath:/db/migration


cicoffee:
  auth:
    jwt:
      expires-in: 3600
      refresh-token-expires-in: 182
      signing-key: W4c3EPAGUnUZqVIQwbaIMJHly9Cdp_66vKgKxL_n9oK2HOg98dNCNclhMID2wqBdY3A7YtAh01wpUjPXZ6PMocmPi67G932WAj_tNFb7QTOO5IZSqGaUKVw7Mpl_IDDFMNcUKASCfpyZs9sM4rM2cTDtDr7Mv1ibCjkdbyEG5Q6_R6crf41FhLlqQuSjnETEvhZoktDmAuU1J_ikpy-9vbQ55y80I5v279hf6YDIy0027EmCFoUteR4KfYeRKTPA7eOdly3biQgGZXtInF5gOiwbZKkFJ5EFulT2QtIne35YBQENeE5OQ0mDILnZb0uTdMcJTUhQ6H7c2NpJNO4NEA
